### ISSUE TITLE
CASPT2 gradient parallelization error - unknown error

### ISSUE THREAD

**Issue by AlexPrihodko** [qsimulate-open/bagel#194]
Hi,

I calculated analytical gradient in CASPT2 (12 active orbitals, 3 states, 63 atoms) using more than one processor (firstly, I used 12 processors, then, when I found a problem, I tried from 1 to 3 processors) and found some error at the end of out-file which doesnn't give any information about itself:

=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 32660 RUNNING AT node-002
=   EXIT CODE: 7
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

Error appeares only when I use two or more procesors. Do you have any ideas, what it can be? 
Thanks in advance for your help.

Input (opt_caspt2_grad.txt):

[opt_caspt2_grad.txt](https://github.com/nubakery/bagel/files/4116902/opt_caspt2_grad.txt)

Output (opt_grad_2pr.txt):

[opt_grad_2pr.txt](https://github.com/nubakery/bagel/files/4116914/opt_grad_2pr.txt)

**Comment by shiozaki** [comment]
You are running all of the MPI processes on the same node. I assume that
you ran out of memory.
