### ISSUE TITLE
Running TestSuits in Parallel?

### ISSUE THREAD

**Issue by yangliu2009** [qsimulate-open/bagel#198]
The installation guid instructs to run './TestSuit --log_level=all' for a test run. The test run passes without any errors for my installation with Redhat 7, Slurm 17, boost/1.72, mvapich2.3.3 and gcc7.2. Does the test run on only one core? If yes, how to test the installation works with mpi? Should we run with "run --mpi=pmi2 ./Testsuits --log_level=all" to test that?

**Comment by shiozaki** [comment]
You can probably run
```
mpirun -n 2 ./Testsuits --log_level=all
```

**Comment by yangliu2009** [comment]
Does the TestSuits works for 3 or more cores? My installation received segmentation fault for 3 or more cores from 'turn --mpi=pmi2 ./TestSuit --log_level=all", but fine with 2 cores. 

I tested the BAGEL directly with 4 cores on test/hf_svp_coulomb.json, but received the following error:
   *** Warning *** Since the number of auxiliary shells is too small, we do not parallelize the Fock builder.
       - 3-index ints prep                         0.00
       - 3-index ints                              0.27
       - 3-index ints post                         0.00
       - Geometry relativistic (total)             0.30
  *** Dirac HF ***
       - 1-electron integrals                      0.10
       - Coulomb: half trans                       0.11
[mpi_rank_1][error_sighandler] Caught error: Segmentation fault (signal 11)
[mpi_rank_3][error_sighandler] Caught error: Segmentation fault (signal 11)
[mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)
[mpi_rank_2][error_sighandler] Caught error: Segmentation fault (signal 11)

I am not sure the error was because of the slurm and mvapich integration, or that Testsuits is not intended to run in parallel on 3 or more cores.

**Comment by shiozaki** [comment]
That's most likely because those tests are too small to be parallelized with 4 processes. Can you try a similar input with a larger molecule? You could check the accuracy against serial runs.

(Yes, the BAGEL should throw reasonable exception... but unfortunately in some cases it doesn't...)

**Comment by yangliu2009** [comment]
Our user tested BAGEL with 16 cores on two nodes and it worked well. So TestSuit probably does not work for 3 and more cores.

**Comment by shiozaki** [comment]
Let me close this for now. I'd say that the test system needs upgrade but it should be done on a separate thread.
