### ISSUE TITLE
Problem with "algorithm" : "noopt" option in CASSCF

### ISSUE THREAD

**Issue by tpitesa** [qsimulate-open/bagel#209]
Dear all,

I tried to perform the CASCI calculation by calling CASSCF with no orbital optimization (I cannot call RASCI or FCI because I want to proceed with such obtained reference states to the XMS-CASPT2 calculation and SMITH allows only HF or CASSCF reference) and the program stops immediately after printing CI vectors (seg. fault) without any error message in output file. It happens regardless the number of states, active space, molecule... Any ideas why this problem occurs? It seems like a bug in "algorithm" : "noopt" option to me or maybe I did something wrong in installation? Thanks a lot!

Best,
Tomislav

**Comment by shiozaki** [comment]
Please post a self-contained input with a small molecule here so I can
reproduce.

**Comment by tpitesa** [comment]
Here you are:


{ "bagel" : [
  
{
  "title" : "molecule",
  "basis" : "aug-cc-pVDZ",
  "df_basis" : "cc-pVDZ-jkfit",
  "angstrom" : true,
  "geometry" : [
    { "atom" : "C",  "xyz" : [   -0.7034280,   -1.1405244,    0.0000000    ] },
    { "atom" : "N",  "xyz" : [   -1.4280570,    0.0000000,    0.0000000    ] },
    { "atom" : "C",  "xyz" : [   -0.7034280,    1.1405244,    0.0000000    ] },
    { "atom" : "C",  "xyz" : [    0.7034280,    1.1405244,   -0.0000000    ] },
    { "atom" : "C",  "xyz" : [    0.7034280,   -1.1405244,   -0.0000000    ] },
    { "atom" : "H",  "xyz" : [   -1.2628864,    2.0811297,   -0.0000000    ] },
    { "atom" : "H",  "xyz" : [    1.2628864,    2.0811297,    0.0000000    ] },
    { "atom" : "H",  "xyz" : [    1.2628864,   -2.0811297,    0.0000000    ] },
    { "atom" : "H",  "xyz" : [   -1.2628864,   -2.0811297,   -0.0000000    ] },
    { "atom" : "N",  "xyz" : [    1.4280570,   -0.0000000,    0.0000000    ] }
  ]
},

{
    "title" : "hf"
},

{
    "title" : "casscf",
    "algorithm" : "noopt",
    "maxiter" :1500,
    "nact" : 8,
    "nclosed" : 16,
    "nstate" : 2
}

]}

**Comment by shiozaki** [comment]
I will fix this when I have time, but in the meantime, add an option "canonical" : true in the casscf/noopt block and the calculation will go through.

**Comment by tpitesa** [comment]
Thanks, this works
