### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wubaihua** [qsimulate-open/bagel#216]
Dear all:
I am trying to install BAGEL on supercomputer. However, the following error will occurred while I run make：

libtool: compile:  mpicxx -DHAVE_CONFIG_H -I. -I../../../src/pt2 -I../.. -I/public1/soft/boost/1_57_0-gcc485//include -I../../.. -DNDEBUG -O3 -mavx -std=c++11 -MT nevpt2/nevpt2.lo -MD -MP -MF nevpt2/.deps/nevpt2.Tpo -c ../../../src/pt2/nevpt2/nevpt2.cc  -fPIC -DPIC -o nevpt2/.libs/nevpt2.o
init2.c:52: MPFR assertion failed: p >= 2 && p <= ((mpfr_prec_t)((mpfr_uprec_t)(~(mpfr_uprec_t)0)>>1))
../../../src/pt2/nevpt2/nevpt2.cc: In member function ‘void bagel::NEVPT2<DataType>::compute() [with DataType = std::complex<double>]’:
../../../src/pt2/nevpt2/nevpt2.cc:928:46: internal compiler error: Aborted
 template class bagel::NEVPT2<complex<double>>;
                                                                                   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/cc6Tr1r4.out file, please attach this to your bugreport.
make[3]: *** [nevpt2/nevpt2.lo] Error 1
make[3]: Leaving directory `/public3/home/sc31119/local/bagel_old/obj/src/pt2'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/public3/home/sc31119/local/bagel_old/obj/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/public3/home/sc31119/local/bagel_old/obj'
make: *** [all] Error 2

How can I solve this problem？Thanks a lot.

**Comment by shiozaki** [comment]
This is an error in the compilers of are using. Use a different version. Later gcc is more stable, I suppose.

**Comment by BidhanChandra** [comment]
While installing I am getting this kind of error

make  all-recursive
make[1]: Entering directory '/home/titan/bagel-1.1.1/obj'
Making all in src
make[2]: Entering directory '/home/titan/bagel-1.1.1/obj/src'
Making all in util
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/util'
Making all in parallel
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/util/parallel'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/util/parallel'
Making all in io
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/util/io'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/util/io'
Making all in input
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/util/input'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/util/input'
Making all in math
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/util/math'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/util/math'
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/util'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/util'
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/util'
Making all in molecule
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/molecule'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/molecule'
Making all in integral
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/integral'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/integral'
Making all in df
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/df'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/df'
Making all in opt
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/opt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/opt'
Making all in grad
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/grad'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/grad'
Making all in pt2
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/pt2'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/pt2'
Making all in wfn
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/wfn'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/wfn'
Making all in scf
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/scf'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/scf'
Making all in multi
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/multi'
Making all in casscf
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/multi/casscf'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/multi/casscf'
Making all in zcasscf
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/multi/zcasscf'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/multi/zcasscf'
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/multi'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/multi'
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/multi'
Making all in smith
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/smith'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/smith'
Making all in prop
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/prop'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/prop'
Making all in ci
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/ci'
Making all in ciutil
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/ci/ciutil'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/ci/ciutil'
Making all in fci
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/ci/fci'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/ci/fci'
Making all in ras
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/ci/ras'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/ci/ras'
Making all in zfci
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/ci/zfci'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/ci/zfci'
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/ci'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/ci'
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/ci'
Making all in response
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/response'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/response'
Making all in asd
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/asd'
Making all in dmrg
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/asd/dmrg'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/asd/dmrg'
Making all in dimer
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/asd/dimer'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/asd/dimer'
Making all in multisite
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/asd/multisite'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/asd/multisite'
Making all in orbital
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/asd/orbital'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/asd/orbital'
make[4]: Entering directory '/home/titan/bagel-1.1.1/obj/src/asd'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/asd'
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/asd'
Making all in mat1e
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/mat1e'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/mat1e'
Making all in basis
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/basis'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/basis'
Making all in periodic
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src/periodic'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src/periodic'
make[3]: Entering directory '/home/titan/bagel-1.1.1/obj/src'
/bin/bash ../libtool  --tag=CXX   --mode=link mpicxx -I../.. -g -O2   -o BAGEL main.o libbagel.la opt/libbagel_opt.la multi/zcasscf/libbagel_zcasscf.la ci/zfci/libbagel_zfci.la ci/fci/libbagel_fci.la ci/ras/libbagel_ras.la response/libbagel_response.la scf/libbagel_scf.la multi/casscf/libbagel_casscf.la pt2/libbagel_pt2.la grad/libbagel_grad.la wfn/libbagel_wfn.la df/libbagel_df.la smith/libbagel_smith.la prop/libbagel_prop.la asd/libbagel_asd.la asd/dmrg/libbagel_asd_dmrg.la asd/orbital/libbagel_asd_orbital.la asd/dimer/libbagel_dimer.la asd/multisite/libbagel_multisite.la ci/ciutil/libbagel_ciutil.la mat1e/libbagel_mat1e.la periodic/libbagel_periodic.la integral/libbagel_integral.la molecule/libbagel_molecule.la util/io/libbagel_io.la util/libbagel_util.la util/parallel/libbagel_parallel.la util/math/libbagel_math.la util/input/libbagel_input.la -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -lboost_unit_test_framework -lboost_regex -lboost_serialization  
libtool: link: mpicxx -I../.. -g -O2 -o .libs/BAGEL main.o  ./.libs/libbagel.so opt/.libs/libbagel_opt.so multi/zcasscf/.libs/libbagel_zcasscf.so ci/zfci/.libs/libbagel_zfci.so ci/fci/.libs/libbagel_fci.so ci/ras/.libs/libbagel_ras.so response/.libs/libbagel_response.so scf/.libs/libbagel_scf.so multi/casscf/.libs/libbagel_casscf.so pt2/.libs/libbagel_pt2.so grad/.libs/libbagel_grad.so wfn/.libs/libbagel_wfn.so df/.libs/libbagel_df.so smith/.libs/libbagel_smith.so prop/.libs/libbagel_prop.so asd/.libs/libbagel_asd.so asd/dmrg/.libs/libbagel_asd_dmrg.so asd/orbital/.libs/libbagel_asd_orbital.so asd/dimer/.libs/libbagel_dimer.so asd/multisite/.libs/libbagel_multisite.so ci/ciutil/.libs/libbagel_ciutil.so mat1e/.libs/libbagel_mat1e.so periodic/.libs/libbagel_periodic.so integral/.libs/libbagel_integral.so molecule/.libs/libbagel_molecule.so util/io/.libs/libbagel_io.so util/.libs/libbagel_util.so util/parallel/.libs/libbagel_parallel.so util/math/.libs/libbagel_math.so util/input/.libs/libbagel_input.so -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -lboost_unit_test_framework -lboost_regex -lboost_serialization -Wl,-rpath -Wl,/usr/local/bagel/lib
main.o: In function `boost::archive::detail::common_iarchive<boost::archive::binary_iarchive>::vload(boost::archive::class_name_type&)':
main.cc:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_15class_name_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_15class_name_typeE]+0x1): undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
main.o: In function `void boost::serialization::throw_exception<boost::archive::archive_exception>(boost::archive::archive_exception const&)':
main.cc:(.text._ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_[_ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_]+0x1d): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::RelFCI::RelFCI(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>, int, int, std::shared_ptr<bagel::ZCoeff_Block const>, bool, bool)'
asd/.libs/libbagel_asd.so: undefined reference to `vtable for bagel::RASCivector_impl<double>'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm3(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm3(int, int) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::ApplyOperator::operator()(double, bagel::RASBlockVectors const&, bagel::RASBlockVectors&, std::vector<bagel::GammaSQ, std::allocator<bagel::GammaSQ> > const&, std::vector<int, std::allocator<int> > const&) const'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::ZCASSecond::ZCASSecond(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZCASNoopt::ZCASNoopt(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASDeterminants::RASDeterminants(int, int, int, int, int, int, int, bool)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivecView_<double>::RASCivecView_(std::shared_ptr<bagel::RASDeterminants const>, double*)'
asd/.libs/libbagel_asd.so: undefined reference to `vtable for bagel::RASCivector<double>'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::FormSigmaRAS::operator()(std::shared_ptr<bagel::Dvector_base<bagel::RASCivector<double> > const>, std::shared_ptr<bagel::MOFile const>, std::vector<int, std::allocator<int> > const&) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `vtable for bagel::ZHarrison'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::CIS::CIS(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::spin() const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::spin_raise_impl(bagel::RASCivecView_<double>, bagel::RASCivecView_<double>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `typeinfo for bagel::ZHarrison'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::RelDvector<std::complex<double> >::extract_state(std::vector<int, std::allocator<int> >) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::RASCI::RASCI(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::RelJop::compute_half[abi:cxx11](std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::ZMatrix const>, bool, bool)'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm2(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::RelDvector<std::complex<double> >::clone() const'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::ZCASSCF::conv_to_ref_(bool) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivector_impl<double>::normalize()'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::Sparse_IJ::Sparse_IJ(std::shared_ptr<bagel::CIStringSet<bagel::RASString, void> const>, std::shared_ptr<bagel::CIStringSet<bagel::RASString, void> const>)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::DenomTask::compute()'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZCASNoopt_London::ZCASNoopt_London(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::spin_lower_impl(bagel::RASCivecView_<double>, bagel::RASCivecView_<double>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm1(int, int) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::spin_lower(std::shared_ptr<bagel::RASDeterminants const>) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::FCI_London::FCI_London(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>, int, int, std::shared_ptr<bagel::ZCoeff_Block const>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm4(int, int) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::ApplyOperator::operator()(double, bagel::RASCivecView_<double>, bagel::RASCivecView_<double>, std::vector<bagel::GammaSQ, std::allocator<bagel::GammaSQ> > const&, std::vector<int, std::allocator<int> > const&) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivector_impl<double>::print(double) const'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::RelJop::compute_full(std::shared_ptr<bagel::ZMatrix const>, std::__cxx11::list<std::shared_ptr<bagel::RelDFHalf>, std::allocator<std::shared_ptr<bagel::RelDFHalf> > >, bool)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZFCI_bare::ZFCI_bare(std::shared_ptr<bagel::CIWfn_<bagel::RelDvector<std::complex<double> >, std::pair<std::shared_ptr<bagel::RelSpace const>, std::shared_ptr<bagel::RelSpace const> > > const>)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::spin_impl(bagel::RASCivecView_<double>, bagel::RASCivecView_<double>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZCASNoopt_base::compute()'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivecView_<double>::data()'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::RASCivector(std::shared_ptr<bagel::RASDeterminants const>)'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm1(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm4(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::FormSigmaRAS::operator()(std::shared_ptr<bagel::Dvector_base<bagel::RASCivector<double> > const>, std::shared_ptr<bagel::Matrix const>, std::shared_ptr<bagel::Matrix const>, std::vector<int, std::allocator<int> > const&) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm2(int, int) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::spin_raise(std::shared_ptr<bagel::RASDeterminants const>) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZCASSecond_London::ZCASSecond_London(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::RASCivector(bagel::RASCivector<double> const&)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector_impl<double>::synchronize(int)'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::rdm34f(int, int, std::shared_ptr<bagel::ZMatrix const>) const'
collect2: error: ld returned 1 exit status
Makefile:533: recipe for target 'BAGEL' failed
make[3]: *** [BAGEL] Error 1
make[3]: Leaving directory '/home/titan/bagel-1.1.1/obj/src'
Makefile:584: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/titan/bagel-1.1.1/obj/src'
Makefile:416: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/titan/bagel-1.1.1/obj'
Makefile:348: recipe for target 'all' failed
make: *** [all] Error 2

can you please help?

**Comment by shiozaki** [comment]
Without seeing all of the configure options I cannot tell, but there are two things to try: (1) add "--enable-static --disable-shared" (2) add "-Wl,--copy-dt-needed-entries -Wl,--no-as-needed" to CXXFLAGS

**Comment by shiozaki** [comment]
Please reopen if you have further question.
