### ISSUE TITLE
MCSCF Density Matrices

### ISSUE THREAD

**Issue by Jyotirmoyray** [qsimulate-open/bagel#217]
Hello, 
     Can you please tell how can I extract MCSCF density matrices from BAGEL? Actually I want transition density matrix to print. Is it possible to extract these information?

**Comment by shiozaki** [comment]
I don't think you can do that without editing the code.
Insert here:
https://github.com/qsimulate-open/bagel/blob/master/src/multi/casscf/cassecond.cc#L164
write the following code (if you are interested in the transition density matrix between state 0 (ground state) and state 1:
```
fci_->compute_rdm12(0, 1);
fci_->rdm1(0, 1)->print(thresh);
fci_->rdm2(0, 1)->print(thresh);
```
you need to set threshold (double). If you want to printout everything, just use some negative number.

**Comment by Jyotirmoyray** [comment]
Thank you sir for your reply. I try this then I will inform you.

**Comment by Jyotirmoyray** [comment]
Sir, 
I am little bit confused. Looking at the code I realized that "thresh()" is a function. So do I need to write "thresh()" instead of "thresh" ? I am fortran guy, c++ is too difficult for me. 
And I didn't understand where to set threshold(double) and which variable I need to make negative.

**Comment by shiozaki** [comment]
Unfortunately, I cannot do further assistance as I am no longer in academia. I suggest that you should do some trials-and-errors or seek help from your colleagues. I will close this issue.
