### ISSUE TITLE
Specifying spin for conical intersection optimizations? 

### ISSUE THREAD

**Issue by chertianser** [qsimulate-open/bagel#220]
Hello,

I believe it is possible to obtain a CASPT2 optimized structure for the T1 state using the "nspin" tag, but I was wondering if it was possible to optimize a S0-T1 conical intersection (or any singlet-triplet CI) using CASPT2. As far as I can tell, the tags for "target" and "target2" only specify the number of the excited state, but contains no information related to "nspin".

Any help would be greatly appreciated!

**Comment by shiozaki** [comment]
Currently, there is no option that allows you to do this. Nuclear gradients for S0 and T1 can be computed separately -- that can be used to evaluate the gradient of average energies and energy differences; if you can use external geometry optimizer, you may be able to optimize for the minimum energy spin crossing point.
