### ISSUE TITLE
Restart for Force calculations 

### ISSUE THREAD

**Issue by abiancar11** [qsimulate-open/bagel#221]
The testcode reported in https://nubakery.org/grad/dynamics.html is working for me, but I have a question:

How to set up the BAGEL input file for force calculations which starts from the wavefunction obtained in the previous calculation?

**Comment by shiozaki** [comment]
Generally, you could use save_ref/load_ref to store/load wave functions. See https://nubakery.org/miscellaneous/save_ref.html  could you try it out?

**Comment by shiozaki** [comment]
Please reopen if you have further questions.
