### ISSUE TITLE
nclosed while using ecp and interfacing with sharc

### ISSUE THREAD

**Issue by BidhanChandra** [qsimulate-open/bagel#222]
1) My system contains two Br atoms. So I want to use lanl2dz ecp for them and cc-pvdz for C, N, O, H. System in total has 160 electrons. If I consider 8e. Then for 8o, what should be nclosed?

160 - 8 =152
so 152/2 = 76 ?? or smaller than that because ecp has been used for Br atoms.

2) I want to interface Bagel with sharc for non-adiabatic dynamics. SHARC is asking for $BAGEL path which will contain bin and lib folder. What should I give?

**Comment by shiozaki** [comment]
ECP in the open-source version is experimental (not optimized) and also does not support nuclear gradients. For Br, I suggest using cc-pvdz basis set. The commercial software that is being developed by QSimulate does support efficient ECP and its nuclear gradients, but currently not publicly available.

Re: SHARC options, please contact the developer of SHARC. I will close this issue.
