### ISSUE TITLE
Problem with  duplicate the results in the ”Communication: Active-space decomposition for molecular dimers“article

### ISSUE THREAD

**Issue by WANGBO428** [qsimulate-open/bagel#223]
Dear developers,

I want to use the ASD method in BAGEL, so I repeated the data in the literature. I would like to ask some questions. Hope to get your help.

The first question is how to calculate CASCI in bagel.  I tried to set the maxiter of the CASSCF module to 0, the algorithm is noopt, but an error occurs, and the error message is Segmentation fault (core dumped). 
The following is my input file, I want to know I want to know how to modify.
{ "bagel" : [

{
  "title" : "molecule",
  "basis" : "cc-pvdz",
  "df_basis" : "cc-pvdz-jkfit",
  "angstrom" : false,
  "geometry" : [
  { "atom" : "C", "xyz" : [      0.000000,      0.000000,      2.641123 ] },
  { "atom" : "C", "xyz" : [      2.287708,      0.000000,      1.320676 ] },
  { "atom" : "C", "xyz" : [      2.287700,      0.000000,     -1.320713 ] },
  { "atom" : "C", "xyz" : [      0.000000,      0.000000,     -2.641147 ] },
  { "atom" : "C", "xyz" : [     -2.287700,      0.000000,     -1.320713 ] },
  { "atom" : "C", "xyz" : [     -2.287708,      0.000000,      1.320676 ] },
  { "atom" : "H", "xyz" : [      4.072213,      0.000000,      2.351647 ] },
  { "atom" : "H", "xyz" : [      4.072215,      0.000000,     -2.351632 ] },
  { "atom" : "H", "xyz" : [      0.000000,      0.000000,     -4.701913 ] },
  { "atom" : "H", "xyz" : [     -4.072215,      0.000000,     -2.351632 ] },
  { "atom" : "H", "xyz" : [     -4.072213,      0.000000,      2.351647 ] },
  { "atom" : "H", "xyz" : [      0.000000,      0.000000,      4.701980 ] },
  { "atom" : "C", "xyz" : [      0.000000,      7.558905,      2.641123 ] },
  { "atom" : "C", "xyz" : [      2.287708,      7.558905,      1.320676 ] },
  { "atom" : "C", "xyz" : [      2.287700,      7.558905,     -1.320713 ] },
  { "atom" : "C", "xyz" : [      0.000000,      7.558905,     -2.641147 ] },
  { "atom" : "C", "xyz" : [     -2.287700,      7.558905,     -1.320713 ] },
  { "atom" : "C", "xyz" : [     -2.287708,      7.558905,      1.320676 ] },
  { "atom" : "H", "xyz" : [      4.072213,      7.558905,      2.351647 ] },
  { "atom" : "H", "xyz" : [      4.072215,      7.558905,     -2.351632 ] },
  { "atom" : "H", "xyz" : [      0.000000,      7.558905,     -4.701913 ] },
  { "atom" : "H", "xyz" : [     -4.072215,      7.558905,     -2.351632 ] },
  { "atom" : "H", "xyz" : [     -4.072213,      7.558905,      2.351647 ] },
  { "atom" : "H", "xyz" : [      0.000000,      7.558905,      4.701980 ] }
  ]
},

{
  "title" : "hf"
},

{
	  "title" : "casscf",
	  "nstate" : 3,
	  "nclosed": 36,
	  "nact" : 12,
          "active" : [33, 38, 39, 40, 41, 42, 43, 44, 45, 46, 59, 60],
	  "algorithm" : "noopt",
	  "maxiter" : 0
},

{
  "title" : "print",
  "file" : "2ben_cas.molden",
  "orbitals" : true
}
]}

The second question is that when testing convergence, using different compositions and sizes of the monomer state bases, the results obtained are inconsistent with those in the literature.
 
I used other packages to calculate the E2-E1 of dimer's CASCI in the full dimer space. which is consistent with the results in the literature with cc-pvdz level.

If the subspace of the monomer is set to 2, and only the singlet state of the monomer is considered, the result of E2-E1 in the literature is about 50 meV, but my result is about 15 meV. 

If the singlet state, CT state, and TT state subspace of the monomer are set to 8, my result is probably only 5 meV, which is obviously inconsistent with the results in the literature. 

I don’t know what went wrong, I sincerely ask for your help.

In the simplest case, only monomer “singlet” (S) states are included, my  input file is as follows，
{ "bagel" : [

{
  "title" : "molecule",
  "basis" : "cc-pvdz",
  "df_basis" : "cc-pvdz-jkfit",
  "angstrom" : false,
  "cartesian" : false,
  "geometry" : [
    {"atom" :"C", "xyz" : [    0.00000000000000,     0.00000000000000,     2.64112304663605] },
    {"atom" :"C", "xyz" : [    2.28770766388446,     0.00000000000000,     1.32067631141874] },
    {"atom" :"C", "xyz" : [    2.28770047235649,     0.00000000000000,    -1.32071294538560] },
    {"atom" :"C", "xyz" : [    0.00000000000000,     0.00000000000000,    -2.64114665444819] },
    {"atom" :"C", "xyz" : [   -2.28770047235649,     0.00000000000000,    -1.32071294538560] },
    {"atom" :"C", "xyz" : [   -2.28770766388446,     0.00000000000000,     1.32067631141874] },
    {"atom" :"H", "xyz" : [    4.07221260176630,     0.00000000000000,     2.35164689765998] },
    {"atom" :"H", "xyz" : [    4.07221517814719,     0.00000000000000,    -2.35163163881380] },
    {"atom" :"H", "xyz" : [    0.00000000000000,     0.00000000000000,    -4.70191324441092] },
    {"atom" :"H", "xyz" : [   -4.07221517814719,     0.00000000000000,    -2.35163163881380] },
    {"atom" :"H", "xyz" : [   -4.07221260176630,     0.00000000000000,     2.35164689765998] },
    {"atom" :"H", "xyz" : [    0.00000000000000,     0.00000000000000,     4.70197960246451] }
  ]
},

{
  "title" : "hf"
},

{
  "title" : "dimerize",
  "angstrom" : true,
  "translate" : [0.0, 4.0, 0.0],
  "dimer_active" : [17, 20, 21, 22, 23, 30],
  "hf" : {
    "thresh" : 1.0e-12
  },
  "localization" : {
    "max_iter" : 50,
    "thresh" : 1.0e-8
  }
},

{
  "title" : "asd",
  "method" : "cas",
  "store_matrix" : false,
  "space" : [
    { "charge" : 0, "spin" : 0, "nstate" : 2}
  ],
  "fci" : {
    "thresh" : 1.0e-6,
    "algorithm" : "kh",
    "nguess" : 400
  },
  "nstates" : 4
},

{
	  "title" : "print",
	   "file" : "S2.molden",
	   "orbitals" : true
}

]}
Thank you!

**Comment by shiozaki** [comment]
For the first part of the question, apparently removing "maxiter" : 0 and adding "canonical" : true in the CASSCF block makes it work. Having to add "cannocal" : true was reported in #209, which I have not been able to fix yet.

Regarding the ASD question, unfortunately, I will not be able to help you troubleshoot; I suggest that you contact Professor Shane Parker directly and see if he is willing to help (https://chemistry.case.edu/faculty/shane-parker/).

**Comment by WANGBO428** [comment]
Thank you!
