### ISSUE TITLE
Error compiling bagel

### ISSUE THREAD

**Issue by angelinesalberto** [qsimulate-open/bagel#231]
Hi, 
I am compiling bagel in a cents7.5

I load the follow libraries:

openmpi-4.1.1
openblas-0.3.6
netlib-scalapack
gcc-8.2.0
boost-1.68.0
netlib-lapack-3.8.0
intel-mkl-2020.0.166-gcc-8.2.0-5sobnda

export CC=/mnt/lustre/ohpc/admin/spack/0.12.1/opt/spack/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-5crd33z6gqv7szyryrrt4rh7c3rzawim/bin/mpicc
export CXX=/mnt/lustre/ohpc/admin/spack/0.12.1/opt/spack/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-5crd33z6gqv7szyryrrt4rh7c3rzawim/bin/mpixx
export FC=/mnt/lustre/ohpc/admin/spack/0.12.1/opt/spack/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-5crd33z6gqv7szyryrrt4rh7c3rzawim/bin/mpifort

git clone https://github.com/nubakery/bagel.git
cd bagel

I execute:
ibtoolize
aclocal
autoconf
autoheader
automake -a

mkdir obj
cd obj

export BOOST_ROOT=/mnt/lustre/ohpc/admin/spack/0.12.1/opt/spack/linux-centos7-x86_64/gcc-8.2.0/boost-1.68.0-guthzyhxysqboxa23uydod6dantk5skd

../configure CXXFLAGS="-DNDEBUG -3 -mavx" --prefix=/mnt/lustre/localsoft/bagel-gcc/ --enable-mkl --with-boost=$BOOST_ROOT --with-mpi=openmpi

The configure is right but when I compile
make -j4 

Finally I get the follow error:
.......
......
libtool: link: rm -fr .libs/libbagel.lax
libtool: link: ( cd ".libs" && rm -f "libbagel.la" && ln -s "../libbagel.la" "libbagel.la" )
/bin/sh ../libtool  --tag=CXX   --mode=link mpicxx -I../.. -DNDEBUG -O3 -mavx  -L/mnt/lustre/ohpc/admin/spack/0.12.1/opt/spack/linux-centos7-x86_64/gcc-8.2.0/boost-1.68.0-guthzyhxysqboxa23uydod6dantk5skd/lib -lcblas -o BAGEL main.o libbagel.la opt/libbagel_opt.la multi/zcasscf/libbagel_zcasscf.la ci/zfci/libbagel_zfci.la ci/fci/libbagel_fci.la ci/ras/libbagel_ras.la response/libbagel_response.la scf/libbagel_scf.la multi/casscf/libbagel_casscf.la pt2/libbagel_pt2.la grad/libbagel_grad.la wfn/libbagel_wfn.la df/libbagel_df.la smith/libbagel_smith.la prop/libbagel_prop.la asd/libbagel_asd.la asd/dmrg/libbagel_asd_dmrg.la asd/orbital/libbagel_asd_orbital.la asd/dimer/libbagel_dimer.la asd/multisite/libbagel_multisite.la ci/ciutil/libbagel_ciutil.la mat1e/libbagel_mat1e.la integral/libbagel_integral.la molecule/libbagel_molecule.la util/io/libbagel_io.la util/libbagel_util.la util/parallel/libbagel_parallel.la util/math/libbagel_math.la util/input/libbagel_input.la -lboost_regex-mt -lboost_unit_test_framework-mt -lboost_serialization-mt -lscalapack
libtool: link: LD_RUN_PATH="/mnt/lustre/localsoft/bagel-gcc/lib:" mpicxx -I../.. -DNDEBUG -O3 -mavx -o .libs/BAGEL main.o  -L/mnt/lustre/ohpc/admin/spack/0.12.1/opt/spack/linux-centos7-x86_64/gcc-8.2.0/boost-1.68.0-guthzyhxysqboxa23uydod6dantk5skd/lib ./.libs/libbagel.so opt/.libs/libbagel_opt.a multi/zcasscf/.libs/libbagel_zcasscf.a ci/zfci/.libs/libbagel_zfci.a ci/fci/.libs/libbagel_fci.a ci/ras/.libs/libbagel_ras.a response/.libs/libbagel_response.a scf/.libs/libbagel_scf.a multi/casscf/.libs/libbagel_casscf.a pt2/.libs/libbagel_pt2.a grad/.libs/libbagel_grad.a wfn/.libs/libbagel_wfn.a df/.libs/libbagel_df.a smith/.libs/libbagel_smith.a prop/.libs/libbagel_prop.a asd/.libs/libbagel_asd.a asd/dmrg/.libs/libbagel_asd_dmrg.a asd/orbital/.libs/libbagel_asd_orbital.a asd/dimer/.libs/libbagel_dimer.a asd/multisite/.libs/libbagel_multisite.a ci/ciutil/.libs/libbagel_ciutil.a mat1e/.libs/libbagel_mat1e.a integral/.libs/libbagel_integral.a molecule/.libs/libbagel_molecule.a util/io/.libs/libbagel_io.a util/.libs/libbagel_util.a util/parallel/.libs/libbagel_parallel.a util/math/.libs/libbagel_math.a util/input/.libs/libbagel_input.a -lcblas -lboost_regex-mt -lboost_unit_test_framework-mt -lboost_serialization-mt -lscalapack
g++: error: ./.libs/libbagel.so: No such file or directory
make[3]: *** [BAGEL] Error 1
make[3]: se sale del directorio `/mnt/lustre/localsoft/bagel/obj/src'
make[2]: *** [all-recursive] Error 1
make[2]: se sale del directorio `/mnt/lustre/localsoft/bagel/obj/src'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio `/mnt/lustre/localsoft/bagel/obj'
make: *** [all] Error 2

Could you help me please?

**Comment by shiozaki** [comment]
Could you delete the entire directories, start from scratch and send all of the logs? (config.log/config.status and entire logs from make/make install). This sort of errors are often due to restarting the compilation after failure and reconfiguration.

**Comment by angelinesalberto** [comment]
I have deleted all and start again and I get the same error.
I send you the logs and the output.
[config.log](https://github.com/qsimulate-open/bagel/files/7469544/config.log)
[config.status.log](https://github.com/qsimulate-open/bagel/files/7469548/config.status.log)

[output_Configure.log](https://github.com/qsimulate-open/bagel/files/7469555/output_Configure.log)
[outputMake.log](https://github.com/qsimulate-open/bagel/files/7469556/outputMake.log)

.Thaks in advance!

**Comment by shiozaki** [comment]
It's a bit odd that your system is building a static library version but then expect libbagel.so to be linked at the end. Make sure that you typed in "libtoolize" instead of "ibtoolize". Next, just in case, please do "autoreconf" at the root directory (alternatively libtoolize, aclocal, autoconf, autoheader, automaker -a). Then try to configure together with "--enable-static --disable-shared" in addition to all of the configure options you used previously. If it fails again, please send the log files again.

**Comment by angelinesalberto** [comment]
It has worked with --enable-static --disable-shared !
Thank you very much!!!
