### ISSUE TITLE
Failing tests on s390x

### ISSUE THREAD

**Issue by utkarsh2102** [qsimulate-open/bagel#240]
Hello,

Thanks for working on bagel. However, one of the test seem to be failing on s390x; here are the logs:
https://autopkgtest.ubuntu.com/results/autopkgtest-jammy/jammy/s390x/b/bagel/20220118_092353_4445c@/log.gz

Could you please take a look and see what we can do to fix the same? TIA! \o/

**Comment by utkarsh2102** [comment]
`he3_svp_asd-dmrg.json` is the failing one, btw. CC: @raymond931118, @shiozaki.

**Comment by utkarsh2102** [comment]
Maybe happening because s390x is big-endian?

**Comment by shiozaki** [comment]
This test is known to fail from time to time as noted in the manual.
https://nubakery.org/quickstart/installation_guide.html#build-bagel
```
One of the tests (ASD-DMRG) is meant to fail.
```
To make it pass, one just has to change the threshold on the noise but it would make the test to run quite a bit longer and therefore it is provided as is. 

Note that BAGEL is strictly standard-compliant and therefore endian etc won't matter.

I will close this issue for now.

**Comment by utkarsh2102** [comment]
Ah, so on Ubuntu and Debian, this fails to build on s390x. Would it make sense if we remove the test during the build for all the architectures?
