### ISSUE TITLE
How to read  moden file in ASD calculations

### ISSUE THREAD

**Issue by WANGBO428** [qsimulate-open/bagel#245]
Dear developer,
In ASD calculations, if I don't want to use the orbital produced by BAGEL, how do I read the orbital from the outside for ASD calculations. Taking bagel/test/benzene_sto3g_asd_T.json as an example, I don't need to do HF for monomer, nor do I need to do dimerization and localization. What form I need to read the orbital, can you give me some advice?

Best,
Bo

**Comment by bessvlai** [comment]
Dear Bo,
I haven't done this with ASD specifically, but you should be able to read a molden file from another program. See information about the molecule block where you can set "basis" to molden. 
Bess

**Comment by WANGBO428** [comment]
First of all thank you for your reply, but I made an attempt, if directly in the "molecule" module will set the "basis" to molden, the program cannot continue to run after ending the "molecule" module, because when doing asd calculations, the local orbital is used, which is the orbital after the "dimerize" module. But there is no way for me to skip the previous calculation step to do the ASD calculation, and this is my confusion now.

**Comment by shiozaki** [comment]
Certainly there’s no option to do what you are describing and you will need to change the code somewhat. One possibility is to contact Prof Shane Parker at Case Western University who wrote this code to seek collaboration.

**Comment by WANGBO428** [comment]
ok，thanks
