### ISSUE TITLE
Visualizing Complex-Valued Molecular Orbitals algorithm

### ISSUE THREAD

**Issue by AMDALI** [qsimulate-open/bagel#250]
Hello there,
I read in the article below **Equation-of-Motion Coupled-Cluster Theory to Model L-edge X-Ray Absorption and Photoelectron Spectra** - https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.0c02027 -  that the algorithm of **Visualizing Complex-Valued Molecular Orbitals** - https://doi.org/10.1021/acs.jpca.9b01134 - was implemented in the  QSimulate-QM...
Is that was in Qsimulate-Open version ?
Thanks.

**Comment by shiozaki** [comment]
It is not in the open version. Should you have an interest in this, please contact info@qsimulate.com about pricing etc. We don’t advertise the commercial version to academic users but there exists an academic license plan.
