### ISSUE TITLE
A problem with iodine

### ISSUE THREAD

**Issue by FreemanTheMaverick** [qsimulate-open/bagel#251]
Dear developers,

I compiled the def2-jkfit to bagel's json format by myself so that I should have been able to deal with molecules containing iodine atoms. However, it seems that there is a bug regarding iodine, which is strange because the example of CuH2 on the manual website runs normally on my node. Here are the input, output and def2-jkfit basis set file. Any help will be appreciated.

[i.json.txt](https://github.com/qsimulate-open/bagel/files/9157781/i.json.txt)
[def2-jkfit.json.txt](https://github.com/qsimulate-open/bagel/files/9157784/def2-jkfit.json.txt)
[i.out.txt](https://github.com/qsimulate-open/bagel/files/9157790/i.out.txt)
[slurm-666851.out.txt](https://github.com/qsimulate-open/bagel/files/9157797/slurm-666851.out.txt)

**Comment by shiozaki** [comment]
Your input is incorrect. Change
```
   "charge":"-1"
```
to
```
   "charge":-1
```
and it would work.

**Comment by FreemanTheMaverick** [comment]
> Your input is incorrect. Change
> 
> ```
>    "charge":"-1"
> ```
> 
> to
> 
> ```
>    "charge":-1
> ```
> 
> and it would work.

https://nubakery.org/molecule/molecule.html#effective-core-potential-ecp-basis-sets

Probably not the cause of the problem, because in the example of CuH2 on this website, "charge":"-1" is written.

I tried several basis sets and df basis sets. It turned out that with sto-3g the computation runs well while with def2-svp-ecp and def2-svp-2c-ecp the computation does not. Whether this problem arose did not depend on whether I used complete or def2-jkfit as the df basis set.

Perhaps it is a matter with the version. Tomorrow, I will upgrade the bagel on my node to the latest version and see what will happen.

**Comment by shiozaki** [comment]
Ok - I see, sorry so your input is still correct for the open-source version.

This input on my QSimulate version does work, so either there is a bug that has since been fixed or there is an issue with the basis file.

The ECP code was completely rewritten in the QSimulate version, so it is hard to backport it to the open source version.

Thanks for reporting.

**Comment by FreemanTheMaverick** [comment]
> Ok - I see, sorry so your input is still correct for the open-source version.
> 
> This input on my QSimulate version does work, so either there is a bug that has since been fixed or there is an issue with the basis file.
> 
> The ECP code was completely rewritten in the QSimulate version, so it is hard to backport it to the open source version.
> 
> Thanks for reporting.

The bug still exists in the current version. This is really weird because the file def2-svp-ecp.json for iodine is in exactly the same format as the file lanl2dz-ecp.json for Cu, but the CuH2 example runs well while iodine does not.

By the way, what is QSimulate? Does it include all the features of bagel? May I apply it to my research?
