### ISSUE TITLE
Dyson method not working

### ISSUE THREAD

**Issue by tnorthey** [qsimulate-open/bagel#254]
Hello,

I installed bagel successfully and all tests pass except 1 in the TestSuite program. However, I am trying to run a Dyson orbital calculation as described on the website https://nubakery.org/miscellaneous/dyson.html

That input file gives the error:

> ERROR: EXCEPTION RAISED:  DYSON : unknown method

I am unclear how to resolve this, so I hope posting this issue can give clarity.
Thank you,
Thomas

**Comment by shiozaki** [comment]
This manual is associated with the latest master branch. The dyson module was added after the latest release; please git clone the repository and compile it, instead of using the zip file of the prior releases.
