### ISSUE TITLE
Relativistic CASSCF without density fitting

### ISSUE THREAD

**Issue by AleksandraLeszczyk** [qsimulate-open/bagel#255]
I want to run a four-component relativistic CASSCF without density-fitting as not all atoms have density-fitting basis sets. I set the `df` keyword to `false`, but the BAGEL still tries to use density fitting.

The minimum example which reproduces the error returns the following output
```
  * using 16 threads per process

  ===============================================================
    BAGEL - Freshly leavened quantum chemistry
  ===============================================================

  *** Geometry ***

  { "atom" : "N", "xyz" : [      0.000000,      0.000000,      0.000000 ] },
  { "atom" : "N", "xyz" : [      0.000000,      0.000000,      2.059801 ] },


  Number of basis functions:       28
  Number of electrons      :       14


    * METHOD: MOLECULE                             0.01

  *** Geometry (Relativistic) ***
Segmentation fault
```

The gdb shows that the error concerns the density-fitting-related files
```
Program received signal SIGSEGV, Segmentation fault.
bagel::ParallelDF::average_3index (this=0x15555554d080) at ../../../src/df/paralleldf.h:97
```

I used the following input
```
{ "bagel" : [

{
  "title" : "molecule",
  "basis" : "cc-pvdz",
  "df" : false,
  "angstrom" : "true",
  "geometry" : [
    { "atom" : "N",  "xyz" : [ 0.0000, 0.0000, 0.0000]},
    { "atom" : "N",  "xyz" : [ 0.0000, 0.0000, 1.09]}
  ]
},

{
  "title" : "zcasscf",
  "df" : false,
  "nclosed" : 4,
  "nact": 6
}
]}
```

Is there any way to use BAGEL without density fitting?

**Comment by xubwa** [comment]
No
________________________________
From: AleksandraLeszczyk ***@***.***>
Sent: Tuesday, August 16, 2022 5:05:38 PM
To: qsimulate-open/bagel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qsimulate-open/bagel] Relativistic CASSCF without density fitting (Issue #255)


I want to run a four-component relativistic CASSCF without density-fitting as not all atoms have density-fitting basis sets. I set the df keyword to false, but the BAGEL still tries to use density fitting.

The minimum example which reproduces the error returns the following output

  * using 16 threads per process

  ===============================================================
    BAGEL - Freshly leavened quantum chemistry
  ===============================================================

  *** Geometry ***

  { "atom" : "N", "xyz" : [      0.000000,      0.000000,      0.000000 ] },
  { "atom" : "N", "xyz" : [      0.000000,      0.000000,      2.059801 ] },


  Number of basis functions:       28
  Number of electrons      :       14


    * METHOD: MOLECULE                             0.01

  *** Geometry (Relativistic) ***
Segmentation fault


The gdb shows that the error concerns the density-fitting-related files

Program received signal SIGSEGV, Segmentation fault.
bagel::ParallelDF::average_3index (this=0x15555554d080) at ../../../src/df/paralleldf.h:97


I used the following input

{ "bagel" : [

{
  "title" : "molecule",
  "basis" : "cc-pvdz",
  "df" : false,
  "angstrom" : "true",
  "geometry" : [
    { "atom" : "N",  "xyz" : [ 0.0000, 0.0000, 0.0000]},
    { "atom" : "N",  "xyz" : [ 0.0000, 0.0000, 1.09]}
  ]
},

{
  "title" : "zcasscf",
  "df" : false,
  "nclosed" : 4,
  "nact": 6
}
]}


Is there any way to use BAGEL without density fitting?

**Comment by shiozaki** [comment]
Density fitting is used throughout the code. If you are computing a small molecule and the efficiency doesnt matter much, use an even tempered fitting basis sets. See src/basis/complete.json for an example. This even tempered basis is crazy large - one can reduce tight and diffuse functions, but you should be able to get an idea.
