### ISSUE TITLE
Some primitives are missing in cc-pvdz

### ISSUE THREAD

**Issue by FreemanTheMaverick** [qsimulate-open/bagel#257]
When I compared the Bagel-provided cc-pvdz.json and the cc-pvdz generated with my script (https://github.com/qsimulate-open/bagel/issues/256#issue-1341673141), I found that some primitives are missing in the former.

For example, there should be four primitives in the first S shell of H, but there are only three in the .json.

**Comment by shiozaki** [comment]
This is not an issue, both conventions span the same space.
