### ISSUE TITLE
geometric optimization end with only one optimization cycle

### ISSUE THREAD

**Issue by ABQTrap** [qsimulate-open/bagel#266]
the BAGEL software was installed smoothly, and the energy and gradient calculations all successfully ended. The problem was the geometric calculation, no matter what kinds of methods, hf or mp2 or casscf, the calculations all normally stopped after one optimization cycle, while the convergence criteria were not met yet. Also the energy change in convergence criteria seem to be not correct. For example, the output file of the"hf_svp_mp2_opt.json" from the test folders. Please check this, many thanks.
[hf_svp_mp2_opt.log](https://github.com/qsimulate-open/bagel/files/10939001/hf_svp_mp2_opt.log)

**Comment by shiozaki** [comment]
The output shows that the geometry is optimized after 5 iterations. Probably you have opt.log in the same directory that has all of the details also.

**Comment by ABQTrap** [comment]
Dear Prof. Shiozaki, Thank you for your reply. You're right, the opt.log has the convergence information and optimized structure, sorry I didn't check the opt.log file. There should be no problem then.
