### ISSUE TITLE
how to perform CASSCF calculation of diradical ?

### ISSUE THREAD

**Issue by ABQTrap** [qsimulate-open/bagel#267]
How to perform CASSCF calculation of diradical using BAGEL software? For example, C4H8 diradical. The molecular orbitals of active space (2e,2o),  occupation numbers, and CASSCF energy of the BAGEL calculations seem to be different from the outcome of ORCA and Gaussian software. I am new to BAGEL software. Did I do something wrong or mistakenly setting the keywords? Thanks a lot.

[c4h8-casscf-orca.zip](https://github.com/qsimulate-open/bagel/files/10950944/c4h8-casscf-orca.zip)
[c4h8-casscf-bagel.zip](https://github.com/qsimulate-open/bagel/files/10950945/c4h8-casscf-bagel.zip)

**Comment by ABQTrap** [comment]
Sorry, I didn't choose the active space correctly, the energies and occupation numbers of BAGEL program are all correct. 

When I tried to perform the geometry optimization for C2H4 double bond twisted transition state, the program ended successfully, but when I wanted to calculate the vibrational frequencies based on the optimized geometry, the output file appeared  an error "ERROR: EXCEPTION RAISED:  Spin decontamination failed." How to avoid this ? Thanks a lot. 
[C2H4-TS-CASSCF-freq-2.log](https://github.com/qsimulate-open/bagel/files/11076170/C2H4-TS-CASSCF-freq-2.log)
[casscf.log](https://github.com/qsimulate-open/bagel/files/11076172/casscf.log)
[freq.log](https://github.com/qsimulate-open/bagel/files/11076173/freq.log)
[previous geometry optimization.log](https://github.com/qsimulate-open/bagel/files/11076174/previous.geometry.optimization.log)

**Comment by ABQTrap** [comment]
Dear all, I found this error was due to the wrong active space setting, after increase the active space, all calculations ran smoothly. 
With analytical gradient, CASPT2 calculations of BAGEL is really fast!
I'm sorry for the inconvenience.
This issue can be closed now.

**Comment by shiozaki** [comment]
Great to know (sorry for not replying earlier)! Enjoy using BAGEL :-)
