### ISSUE TITLE
Bagel installation : Boost regex library 

### ISSUE THREAD

**Issue by satyam2709** [qsimulate-open/bagel#271]
Dear Developers:

I am trying to install Bagel. In the newer version (V1.2) of bagel, the config file is giving this error: **configure: error: Could not find a version of the Boost::Regex library!****** 

I have installed the boost librarry, and they are also defined in .bashrc script. I am attaching the config file. 

I have also tried the V1.1, the config works fine, but there is an issue with make file.
[config.log](https://github.com/qsimulate-open/bagel/files/12768624/config.log)

**Comment by shiozaki** [comment]
You want to make sure that libboost_regex***.so is under /usr/local/boost/lib. The code that checks Boost components is widely used (not our own) and likely fine. I am closing the issue.
