### ISSUE TITLE
How to get converged Lagrange multiplier in CASSCF

### ISSUE THREAD

**Issue by lizhuzh** [qsimulate-open/bagel#273]
Hi bagel developers,

Is there anyway to modify the source code so that it can print out the converged Lagrange multiplier for coupled perturbed (single state or state-averaged) CASSCF equation? If so, which section should I take a look at?

Thanks in advance,
Lizhu

**Comment by shiozaki** [comment]
There is no official way of doing it, although you can hack the code to dump it. Unfortunately, we cannot provide fee-free user support. You may want to write to some of the BAGEL developers in academia.
