### ISSUE TITLE
Bagel Installation error in make 

### ISSUE THREAD

**Issue by satyam2709** [qsimulate-open/bagel#277]
Dear Developer:

I have tried again for bagel installation with the config : ../configure CXXFLAGS="-DNDEBUG -O3 -mavx"  --with-boost=$BOOST_ROOT --with-mpi=mvapich --disable-shared --enable-static. The config was successful. When I am doing make then getting the following error. 

/usr/bin/ld: unblocked.cc:(.text+0x179d): undefined reference to `zgeru_'
/usr/bin/ld: unblocked.cc:(.text+0x1814): undefined reference to `zgeru_'
/usr/bin/ld: unblocked.cc:(.text+0x18a2): undefined reference to `zgemv_'
/usr/bin/ld: unblocked.cc:(.text+0x1919): undefined reference to `zgeru_'
/usr/bin/ld: unblocked.cc:(.text+0x19a7): undefined reference to `zgemv_'
/usr/bin/ld: unblocked.cc:(.text+0x1a1e): undefined reference to `zgeru_'
/usr/bin/ld: unblocked.cc:(.text+0x1aa3): undefined reference to `zrot_'
/usr/bin/ld: unblocked.cc:(.text+0x1b14): undefined reference to `zrot_'
/usr/bin/ld: unblocked.cc:(.text+0x1ba1): undefined reference to `zrot_'
/usr/bin/ld: unblocked.cc:(.text+0x1c0a): undefined reference to `zrot_'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:547: BAGEL] Error 1
make[3]: Leaving directory '/home/koushik/Bagel-Satyam/bagel/bagel-master/obj/src'
make[2]: *** [Makefile:625: all-recursive] Error 1
make[2]: Leaving directory '/home/koushik/Bagel-Satyam/bagel/bagel-master/obj/src'
make[1]: *** [Makefile:422: all-recursive] Error 1
make[1]: Leaving directory '/home/koushik/Bagel-Satyam/bagel/bagel-master/obj'
make: *** [Makefile:354: all] Error 2

Kindly help me. 

with regards
Satyam

**Comment by shiozaki** [comment]
The issue above is related to your installation of the BLAS libraries. Please consult with your system administrator. If you are using your own machine, I suggest installing MKL and setting the runtime environment properly. There are ample resources online.
