### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by AngeloRaymondRossi** [qsimulate-open/bagel#282]
Good Morning,

I am hoping you can help me to correct a compiling issue with bagel.  I have included the log file which yielded no errors and the make log file which shows what happened.

I understand you are busy, but successfully compiling and using bagel is very important to our project, including two other faculty and graduate students.

I am using a Lenovo laptop with Intel XEON processor.  Debian 12 is the operating system with SID at the bleeding edge.

Sat Mar 23 07:18:58 [rossi@debian12 ~]$inxi -SA
System:
  Host: debian12 Kernel: 6.6.15-amd64 arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Debian GNU/Linux trixie/sid
Audio:
  Device-1: Intel Tiger Lake-H HD Audio driver: sof-audio-pci-intel-tgl
  Device-2: NVIDIA GA104 High Definition Audio driver: snd_hda_intel
  API: ALSA v: k6.6.15-amd64 status: kernel-api
  Server-1: PipeWire v: 1.0.3 status: active

[config.log](https://github.com/qsimulate-open/bagel/files/14731365/config.log)
[compile-problem.txt](https://github.com/qsimulate-open/bagel/files/14731368/compile-problem.txt)

Thanks so much for any help you can provide.

A. R. Rossi
https://angeloraymondrossi.github.io/

**Comment by AngeloRaymondRossi** [comment]
Please ignore the above comment.  I found a newer version of bagel, and I am retrying the install.  It is missing the 
cblas libraries, but I am almost there..  In addition, debian has a version of bagel, and I installed and ran it with no problem.  But, I need to install it myself on our Linux cluster to run in parallel.

**Comment by shiozaki** [comment]
Thank you for letting me know! I hope you enjoy using BAGEL. Let me close the issue.
