### ISSUE TITLE
The correct signs at determinants in CASSCF

### ISSUE THREAD

**Issue by valievrashid** [qsimulate-open/bagel#283]
Hello!

The BAGEL shows that the singlet as 
   * ci vector, state   0, <S^2> = -0.0000
       2.22    -0.3770972097
       22.2     0.3769508540
       22ab    -0.3416597386
       22ba    -0.3416597386
       ba22    -0.3389500020
       ab22    -0.3389500020
    
I know the singlet is unsymmetric combination of 22ab and 22ba, but here I see the same sign at these two determinants. The same for ba22 and ab22.

I try to build the wavefunction with changing the signs as

Pshi=-0.3770972097*[2.22]+ 0.3769508540*[22.2]- 0.3416597386*[22ab-22ba]-0.3389500020*[ ab22- ba22].

Is it correct?  I understand the true signs respect to each determinants are very important to calculate the matrix elements using this wavefunction.

**Comment by shiozaki** [comment]
In Bagel the determinants are represented as (alpha electrons)(beta electrons) in this order. So 22ab is (1,2,3)(1,2,4), 22ba is (1,2,4)(1,2,3). The coefficients are consistent with this convention. Your expectation of sign is probably coming from the fact that you have a different ordering of electrons in your mind.

**Comment by valievrashid** [comment]
Many thanks! Now I understand!
