### ISSUE TITLE
nacmtype 

### ISSUE THREAD

**Issue by Deping-Hu** [qsimulate-open/bagel#284]
Hello,

I notice there are several options for the "nacmtype" keyword, I'm a little confused about the "full" and "interstate", Could you please tell me what's the difference between these two options? Thanks.

Best,

Deping

**Comment by shiozaki** [comment]
You can take a look at this paper https://arxiv.org/pdf/1701.02259

Generally "interstate" coupling implies that one excludes orbital relaxation terms. (32a) is full, (32b) is interstate the latter of which ignores (32c). Hope this helps. Let me close this issue.

**Comment by Deping-Hu** [comment]
Thanks a lot for your reply. 

So if I want to use the non-adiabatic coupling at the XMS-CASPT2 level to perform the surface hopping dynamics, which one I should use? "full" or "interstate"?

I noted in this paper, the "interstate" was used to optimize the conical intersection.

Best,
Deping

**Comment by shiozaki** [comment]
It must be full. https://arxiv.org/pdf/1706.00156 These things have been studied by many people in the past and you should study a bit

**Comment by Deping-Hu** [comment]
Thanks
