### ISSUE TITLE
Transition dipole moments

### ISSUE THREAD

**Issue by Physfock** [qsimulate-open/bagel#285]
Dear developers,

Could you please advise on how to calculate the transition dipole moment between excited states in a magnetic field within the zcasscf approach? If this is not possible, could you also provide guidance on how to save the wave functions and calculate it manually?

Thank you in advance for your assistance.

**Comment by shiozaki** [comment]
Sorry for the late reply. I believe that the transition dipole moment is not explicitly computed in zcasscf, as transition density matrices are not necessary to optimize the wave function. The wave function is saved in the RelReference object generated by conv_to_ref_, and if you are lucky, the `rdm1` function will return 1RDM that you can use to compute the transition dipole moment. https://github.com/qsimulate-open/bagel/blob/master/src/wfn/relreference.cc#L153
These were written for the relativistic case with no magnetic field in mind, so you will need to inspect carefully to see if this is what you want.

Unfortunately, I cannot help you further, but you could try to contact some of the academic researchers who are familiar with the BAGEL source code. Hope this helps

PS: I thought this ZCASSCF with magnetic field was cool in that you can directly compete the Zeeman splitting. I never pushed it so it's good that you seem to be interested in it. Good luck! Let me close the issue.
